language: python
python:
- '3.8'
- '3.9'
env:
- RECIPIENT=3MyGpJh6Bb8auF3HtSr2dSJjqQVxgqLynpK
- HASH=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
- LEASE_ID=6XmeG7SRWiw8pD6Uad6D9AAaY354v5TV6AJMhPpHMkqy

install:
  - pip3 install .
  - pip3 install --upgrade build
script:
- lto
- ACCOUNT=$(lto accounts create)
- lto accounts list && lto accounts list | grep -q $ACCOUNT
- lto node status
- lto balance 3JugjxT51cTjWAsgnQK4SpmMqK6qua1VpXH
- lto anchor --hash $HASH --no-broadcast
- lto association issue --recipient $RECIPIENT --type 1 --hash $HASH --no-broadcast
- lto association revoke --recipient $RECIPIENT --type 1 --hash $HASH --no-broadcast
- lto transfer --recipient $RECIPIENT --amount 742.6 --no-broadcast
- echo -e "3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj 742.6\n3NBC7ETcdPbf4QAXSop5UCJ53yX34aGPXoz 2184.2" | lto mass-transfer --no-broadcast
- lto lease create --recipient $RECIPIENT --amount 742.6 --no-broadcast
- lto lease cancel --leaseid $LEASE_ID --no-broadcast
- lto sponsorship create --recipient $RECIPIENT --no-broadcast
- lto sponsorship cancel --recipient $RECIPIENT --no-broadcast
- python3 -m build

deploy:
  provider: pypi
  username: __token__
  password:
    secure: JYdEANwgSg3fCbAoQiQp23WC36oqsmZii0OmUQgFn9RwzjCcjV+zOqKaA6Xsq6V4qcVLHEyqjz+vMjQzLiSqxYcgvjXqETFEJ7Y5YrLYMDibZGoST59V3I9rdSQI8BwWggIVERflvVWGPA6nRP+nI2NZy4rvbw73MjcUdeBzBJ7yIhaQfQ46XXaQIBp907D4eH6Uyy3wRzSsNxfJKDJVcYMkHn1BPKpTdPtKNx6P7/OpJ6FOVl3EA2OyBExIXjvqTFjdpJgvGL2OfWbedUBLoPnC2Vq4eV0inptSEZ9jk0pPsM2t36Eo7Fpbhehryr/TI79B6jAFeIujE6Z1c3cBGGPNk4oV7T7YQ7SG2JekaJU2Aak+ZyKTvsRI7ZbmfijuKUzmK9POowY+PqiIX2q5RjKtQmRPbicF3WJJxufssj3v0uxUzgYGmrNvqWiDW8AW7sTPy89gyhVWIrQzlA92AV7ql/861PYXsfyKfXBvfeutgKeLzkYQ3M+yb6Jov0JD/XdZK+Zzu1bESeKKL4FPYTK44mCEp77zJAprYH+Xr2xy9J7v8ScwImA3oeQYWkN5se594kkiDJsg7POQYJoOIXFNC9OWlXRLVWut1a3qYTC7CydO5OZtpbLddzyQyWLso2U+G6lpKfRoH1sSN/61qoQ+GcXQY1NnvJywTDye0Oo=
  on:
    tags: true
  skip_cleanup: true
