language: python
python:
- '3.8'
- '3.9'
env:
- RECIPIENT=3MyGpJh6Bb8auF3HtSr2dSJjqQVxgqLynpK
- HASH=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
- LEASE_ID=6XmeG7SRWiw8pD6Uad6D9AAaY354v5TV6AJMhPpHMkqy

install:
  - pip3 install .
script:
- lto
- ACCOUNT=$(lto accounts create)
- lto accounts list && lto accounts list | grep -q $ACCOUNT
- lto node status
- lto balance 3JugjxT51cTjWAsgnQK4SpmMqK6qua1VpXH
- lto anchor --hash $HASH --no-broadcast
- lto association issue --recipient $RECIPIENT --type 1 --hash $HASH --no-broadcast
- lto association revoke --recipient $RECIPIENT --type 1 --hash $HASH --no-broadcast
- lto transfer --recipient $RECIPIENT --amount 742.6 --no-broadcast
- echo -e "3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj 742.6\n3NBC7ETcdPbf4QAXSop5UCJ53yX34aGPXoz 2184.2" | lto mass-transfer --no-broadcast
- lto lease create --recipient $RECIPIENT --amount 742.6 --no-broadcast
- lto lease cancel --leaseid $LEASE_ID --no-broadcast
- lto sponsorship create --recipient $RECIPIENT --no-broadcast
- lto sponsorship cancel --recipient $RECIPIENT --no-broadcast

deploy:
  provider: pypi
  username: __token__
  password:
    secure: Ga+rje+j3zf9Rvm3qglgpJycew9rU38ROytMjciqVTD+n2oqpaQRWTCtAmvooE5+hFHXJDV1MW9rTijaBXucCvj12YLz4YqU5arU/NLvKPhJTZx8eaIUjWf8VMcZrYmENVyea9LE0zW9gKGmKLX720bAhMM4WOnel6a69Lo4WiNDbZyKd9J99rZbMc2Nyi1Bxx2XN1YX3Qsme4OR5C3a1rDZNOs8jSCFc7Nuwfes1hk0MSP3VMVHbCUwJLdoMI0Bp8YoRmyhAXGaH5Qz1YxTdZa3/zXRVSL9wruxGH3/o+bmeVR+cPLIxtQhIKgbMDMCf2g782jjKF7EWZ7727R/HOWxpHks0DaXTBgvGL515MsK3CcAbBUFLF/RjoYJ/8lVodE2jRzJ5gGivghn8rGuwcOB6PoNV1edDmlrP3aOWIwur5uK1atAH41qGBLJKZr7EhLXX39MuK52kjwWFl14onisRFbM7R3DEtPRYvskH5vpWJIrQ1wAGkGQeh+eophplTfCGa3fiZfpod05XD4rUgtimXVSlwRLw5dWoJCpo0XcI6lcaf61glofbV291y0Uhbtt1LN6f9dB5VCoSHv+qTKZ8306YMtkUdm8rZ06ldB2PaG5Lum44Y9qAjXL3d3Z0pPRrw8Kye+llXnjfOM90B5heNZz3HPbJHxlixeqzBw=
  on:
    tags: true
  distributions: sdist bdist_wheel
  cleanup: true
